
// Code generated by stanc v2.27.0
#include <stan/model/model_header.hpp>
namespace counts_kriging_model_namespace {

using stan::io::dump;
using stan::model::assign;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 61> locations_array__ = 
{" (found before start of program)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 31, column 2 to column 13)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 32, column 2 to column 13)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 34, column 2 to column 28)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 35, column 2 to column 18)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 37, column 2 to column 20)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 38, column 2 to column 22)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 39, column 2 to column 16)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 44, column 2 to column 14)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 46, column 11 to column 12)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 46, column 14 to column 15)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 46, column 4 to column 21)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 47, column 11 to column 12)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 47, column 14 to column 15)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 47, column 4 to column 49)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 51, column 6 to column 32)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 50, column 4 to line 51, column 32)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 53, column 4 to column 32)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 54, column 4 to column 18)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 45, column 2 to line 55, column 3)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 75, column 2 to column 74)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 61, column 2 to column 107)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 63, column 2 to column 24)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 64, column 2 to column 23)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 65, column 2 to column 21)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 67, column 2 to column 25)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 68, column 2 to column 25)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 69, column 2 to column 25)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 70, column 2 to column 32)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 2, column 2 to column 17)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 3, column 2 to column 30)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 4, column 14 to column 19)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 4, column 2 to column 21)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 6, column 2 to column 23)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 7, column 30 to column 37)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 7, column 2 to column 39)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 8, column 30 to column 37)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 8, column 2 to column 39)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 10, column 10 to column 11)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 10, column 2 to column 13)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 11, column 10 to column 11)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 11, column 2 to column 13)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 13, column 17 to column 22)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 13, column 2 to column 24)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 14, column 18 to column 19)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 14, column 2 to column 23)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 15, column 9 to column 10)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 15, column 2 to column 14)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 20, column 9 to column 10)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 20, column 2 to column 27)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 21, column 2 to column 20)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 23, column 18 to column 19)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 23, column 2 to column 21)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 25, column 4 to column 20)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 26, column 4 to column 20)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 24, column 17 to line 27, column 3)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 24, column 2 to line 27, column 3)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 35, column 9 to column 10)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 39, column 9 to column 10)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 44, column 9 to column 10)",
 " (in '/home/js/programs/jx/jx/stanmodels/counts_kriging.stan', line 75, column 9 to column 10)"};



class counts_kriging_model final : public model_base_crtp<counts_kriging_model> {

 private:
  int N;
  int N_obs;
  std::vector<int> obs_idx;
  int N_edges;
  std::vector<int> node1;
  std::vector<int> node2;
  std::vector<double> X1;
  std::vector<double> X2;
  std::vector<int> y;
  Eigen::Matrix<double, -1, 1> E__;
  Eigen::Matrix<double, -1, 1> x__;
  Eigen::Matrix<double, -1, 1> log_E__;
  double delta;
  std::vector<Eigen::Matrix<double, 1, -1>> X; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> E{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> x{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> log_E{nullptr, 0};
 
 public:
  ~counts_kriging_model() { }
  
  inline std::string model_name() const final { return "counts_kriging_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.27.0", "stancflags = "};
  }
  
  
  counts_kriging_model(stan::io::var_context& context__,
                       unsigned int random_seed__ = 0,
                       std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "counts_kriging_model_namespace::counts_kriging_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 29;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 29;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 29;
      check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 30;
      context__.validate_dims("data initialization","N_obs","int",
           std::vector<size_t>{});
      N_obs = std::numeric_limits<int>::min();
      
      current_statement__ = 30;
      N_obs = context__.vals_i("N_obs")[(1 - 1)];
      current_statement__ = 30;
      check_greater_or_equal(function__, "N_obs", N_obs, 0);
      current_statement__ = 30;
      check_less_or_equal(function__, "N_obs", N_obs, N);
      current_statement__ = 31;
      validate_non_negative_index("obs_idx", "N_obs", N_obs);
      current_statement__ = 32;
      context__.validate_dims("data initialization","obs_idx","int",
           std::vector<size_t>{static_cast<size_t>(N_obs)});
      obs_idx = std::vector<int>(N_obs, std::numeric_limits<int>::min());
      
      current_statement__ = 32;
      obs_idx = context__.vals_i("obs_idx");
      current_statement__ = 33;
      context__.validate_dims("data initialization","N_edges","int",
           std::vector<size_t>{});
      N_edges = std::numeric_limits<int>::min();
      
      current_statement__ = 33;
      N_edges = context__.vals_i("N_edges")[(1 - 1)];
      current_statement__ = 33;
      check_greater_or_equal(function__, "N_edges", N_edges, 0);
      current_statement__ = 34;
      validate_non_negative_index("node1", "N_edges", N_edges);
      current_statement__ = 35;
      context__.validate_dims("data initialization","node1","int",
           std::vector<size_t>{static_cast<size_t>(N_edges)});
      node1 = std::vector<int>(N_edges, std::numeric_limits<int>::min());
      
      current_statement__ = 35;
      node1 = context__.vals_i("node1");
      current_statement__ = 35;
      for (int sym1__ = 1; sym1__ <= N_edges; ++sym1__) {
        current_statement__ = 35;
        check_greater_or_equal(function__, "node1[sym1__]",
                               node1[(sym1__ - 1)], 1);
      }
      current_statement__ = 35;
      for (int sym1__ = 1; sym1__ <= N_edges; ++sym1__) {
        current_statement__ = 35;
        check_less_or_equal(function__, "node1[sym1__]", node1[(sym1__ - 1)],
                            N);
      }
      current_statement__ = 36;
      validate_non_negative_index("node2", "N_edges", N_edges);
      current_statement__ = 37;
      context__.validate_dims("data initialization","node2","int",
           std::vector<size_t>{static_cast<size_t>(N_edges)});
      node2 = std::vector<int>(N_edges, std::numeric_limits<int>::min());
      
      current_statement__ = 37;
      node2 = context__.vals_i("node2");
      current_statement__ = 37;
      for (int sym1__ = 1; sym1__ <= N_edges; ++sym1__) {
        current_statement__ = 37;
        check_greater_or_equal(function__, "node2[sym1__]",
                               node2[(sym1__ - 1)], 1);
      }
      current_statement__ = 37;
      for (int sym1__ = 1; sym1__ <= N_edges; ++sym1__) {
        current_statement__ = 37;
        check_less_or_equal(function__, "node2[sym1__]", node2[(sym1__ - 1)],
                            N);
      }
      current_statement__ = 38;
      validate_non_negative_index("X1", "N", N);
      current_statement__ = 39;
      context__.validate_dims("data initialization","X1","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      X1 = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 39;
      X1 = context__.vals_r("X1");
      current_statement__ = 40;
      validate_non_negative_index("X2", "N", N);
      current_statement__ = 41;
      context__.validate_dims("data initialization","X2","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      X2 = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 41;
      X2 = context__.vals_r("X2");
      current_statement__ = 42;
      validate_non_negative_index("y", "N_obs", N_obs);
      current_statement__ = 43;
      context__.validate_dims("data initialization","y","int",
           std::vector<size_t>{static_cast<size_t>(N_obs)});
      y = std::vector<int>(N_obs, std::numeric_limits<int>::min());
      
      current_statement__ = 43;
      y = context__.vals_i("y");
      current_statement__ = 43;
      for (int sym1__ = 1; sym1__ <= N_obs; ++sym1__) {
        current_statement__ = 43;
        check_greater_or_equal(function__, "y[sym1__]", y[(sym1__ - 1)], 0);
      }
      current_statement__ = 44;
      validate_non_negative_index("E", "N", N);
      current_statement__ = 45;
      context__.validate_dims("data initialization","E","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      E__ = Eigen::Matrix<double, -1, 1>(N);
      new (&E) Eigen::Map<Eigen::Matrix<double, -1, 1>>(E__.data(), N);
      
      {
        std::vector<local_scalar_t__> E_flat__;
        current_statement__ = 45;
        E_flat__ = context__.vals_r("E");
        current_statement__ = 45;
        pos__ = 1;
        current_statement__ = 45;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 45;
          assign(E, E_flat__[(pos__ - 1)],
            "assigning variable E", index_uni(sym1__));
          current_statement__ = 45;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 45;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 45;
        check_greater_or_equal(function__, "E[sym1__]", E[(sym1__ - 1)], 0);
      }
      current_statement__ = 46;
      validate_non_negative_index("x", "N", N);
      current_statement__ = 47;
      context__.validate_dims("data initialization","x","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      x__ = Eigen::Matrix<double, -1, 1>(N);
      new (&x) Eigen::Map<Eigen::Matrix<double, -1, 1>>(x__.data(), N);
      
      {
        std::vector<local_scalar_t__> x_flat__;
        current_statement__ = 47;
        x_flat__ = context__.vals_r("x");
        current_statement__ = 47;
        pos__ = 1;
        current_statement__ = 47;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 47;
          assign(x, x_flat__[(pos__ - 1)],
            "assigning variable x", index_uni(sym1__));
          current_statement__ = 47;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 48;
      validate_non_negative_index("log_E", "N", N);
      current_statement__ = 49;
      log_E__ = Eigen::Matrix<double, -1, 1>(N);
      new (&log_E) Eigen::Map<Eigen::Matrix<double, -1, 1>>(log_E__.data(), N);
      stan::math::fill(log_E, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 49;
      assign(log_E, stan::math::log(E), "assigning variable log_E");
      current_statement__ = 50;
      delta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 50;
      delta = 1e-9;
      current_statement__ = 51;
      validate_non_negative_index("X", "N", N);
      current_statement__ = 52;
      X = std::vector<Eigen::Matrix<double, 1, -1>>(N, Eigen::Matrix<double, 1, -1>(2));
      stan::math::fill(X, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 56;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 53;
        assign(X, rvalue(X1, "X1", index_uni(n)),
          "assigning variable X", index_uni(n), index_uni(1));
        current_statement__ = 54;
        assign(X, rvalue(X2, "X2", index_uni(n)),
          "assigning variable X", index_uni(n), index_uni(2));
      }
      current_statement__ = 57;
      validate_non_negative_index("theta", "N", N);
      current_statement__ = 58;
      validate_non_negative_index("eta", "N", N);
      current_statement__ = 59;
      validate_non_negative_index("f", "N", N);
      current_statement__ = 60;
      validate_non_negative_index("mu", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 1 + 1 + 1 + N + 1 + 1 + N;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "counts_kriging_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ beta0;
      beta0 = DUMMY_VAR__;
      
      current_statement__ = 1;
      beta0 = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta1;
      beta1 = DUMMY_VAR__;
      
      current_statement__ = 2;
      beta1 = in__.template read<local_scalar_t__>();
      local_scalar_t__ sigma_theta;
      sigma_theta = DUMMY_VAR__;
      
      current_statement__ = 3;
      sigma_theta = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                      0, lp__);
      Eigen::Matrix<local_scalar_t__, -1, 1> theta;
      theta = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      stan::math::fill(theta, DUMMY_VAR__);
      
      current_statement__ = 4;
      theta = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(N);
      local_scalar_t__ rho;
      rho = DUMMY_VAR__;
      
      current_statement__ = 5;
      rho = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      local_scalar_t__ alpha;
      alpha = DUMMY_VAR__;
      
      current_statement__ = 6;
      alpha = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      Eigen::Matrix<local_scalar_t__, -1, 1> eta;
      eta = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      stan::math::fill(eta, DUMMY_VAR__);
      
      current_statement__ = 7;
      eta = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(N);
      Eigen::Matrix<local_scalar_t__, -1, 1> f;
      f = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      stan::math::fill(f, DUMMY_VAR__);
      
      {
        current_statement__ = 9;
        validate_non_negative_index("L_K", "N", N);
        current_statement__ = 10;
        validate_non_negative_index("L_K", "N", N);
        Eigen::Matrix<local_scalar_t__, -1, -1> L_K;
        L_K = Eigen::Matrix<local_scalar_t__, -1, -1>(N, N);
        stan::math::fill(L_K, DUMMY_VAR__);
        
        current_statement__ = 12;
        validate_non_negative_index("K", "N", N);
        current_statement__ = 13;
        validate_non_negative_index("K", "N", N);
        Eigen::Matrix<local_scalar_t__, -1, -1> K;
        K = Eigen::Matrix<local_scalar_t__, -1, -1>(N, N);
        stan::math::fill(K, DUMMY_VAR__);
        
        current_statement__ = 14;
        assign(K, cov_exp_quad(X, alpha, rho), "assigning variable K");
        current_statement__ = 16;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 15;
          assign(K, (rvalue(K, "K", index_uni(n), index_uni(n)) + delta),
            "assigning variable K", index_uni(n), index_uni(n));
        }
        current_statement__ = 17;
        assign(L_K, cholesky_decompose(K), "assigning variable L_K");
        current_statement__ = 18;
        assign(f, multiply(L_K, eta), "assigning variable f");
      }
      {
        current_statement__ = 21;
        lp_accum__.add(
          poisson_log_lpmf<propto__>(y,
            add(
              add(
                add(add(rvalue(log_E, "log_E", index_multi(obs_idx)), beta0),
                  multiply(beta1, rvalue(x, "x", index_multi(obs_idx)))),
                rvalue(f, "f", index_multi(obs_idx))),
              multiply(rvalue(theta, "theta", index_multi(obs_idx)),
                sigma_theta))));
        current_statement__ = 22;
        lp_accum__.add(inv_gamma_lpdf<propto__>(rho, 5, 5));
        current_statement__ = 23;
        lp_accum__.add(std_normal_lpdf<propto__>(alpha));
        current_statement__ = 24;
        lp_accum__.add(std_normal_lpdf<propto__>(eta));
        current_statement__ = 25;
        lp_accum__.add(normal_lpdf<propto__>(beta0, 0., 1.));
        current_statement__ = 26;
        lp_accum__.add(normal_lpdf<propto__>(beta1, 0., 1.));
        current_statement__ = 27;
        lp_accum__.add(normal_lpdf<propto__>(theta, 0., 1.));
        current_statement__ = 28;
        lp_accum__.add(exponential_lpdf<propto__>(sigma_theta, 1.));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "counts_kriging_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double beta0;
      beta0 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      beta0 = in__.template read<local_scalar_t__>();
      double beta1;
      beta1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      beta1 = in__.template read<local_scalar_t__>();
      double sigma_theta;
      sigma_theta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      sigma_theta = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                      0, lp__);
      Eigen::Matrix<double, -1, 1> theta;
      theta = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(theta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 4;
      theta = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(N);
      double rho;
      rho = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      rho = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      double alpha;
      alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 6;
      alpha = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      Eigen::Matrix<double, -1, 1> eta;
      eta = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(eta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 7;
      eta = in__.template read<Eigen::Matrix<local_scalar_t__, -1, 1>>(N);
      Eigen::Matrix<double, -1, 1> f;
      f = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(f, std::numeric_limits<double>::quiet_NaN());
      
      vars__.emplace_back(beta0);
      vars__.emplace_back(beta1);
      vars__.emplace_back(sigma_theta);
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(theta[(sym1__ - 1)]);
      }
      vars__.emplace_back(rho);
      vars__.emplace_back(alpha);
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(eta[(sym1__ - 1)]);
      }
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      {
        current_statement__ = 9;
        validate_non_negative_index("L_K", "N", N);
        current_statement__ = 10;
        validate_non_negative_index("L_K", "N", N);
        Eigen::Matrix<double, -1, -1> L_K;
        L_K = Eigen::Matrix<double, -1, -1>(N, N);
        stan::math::fill(L_K, std::numeric_limits<double>::quiet_NaN());
        
        current_statement__ = 12;
        validate_non_negative_index("K", "N", N);
        current_statement__ = 13;
        validate_non_negative_index("K", "N", N);
        Eigen::Matrix<double, -1, -1> K;
        K = Eigen::Matrix<double, -1, -1>(N, N);
        stan::math::fill(K, std::numeric_limits<double>::quiet_NaN());
        
        current_statement__ = 14;
        assign(K, cov_exp_quad(X, alpha, rho), "assigning variable K");
        current_statement__ = 16;
        for (int n = 1; n <= N; ++n) {
          current_statement__ = 15;
          assign(K, (rvalue(K, "K", index_uni(n), index_uni(n)) + delta),
            "assigning variable K", index_uni(n), index_uni(n));
        }
        current_statement__ = 17;
        assign(L_K, cholesky_decompose(K), "assigning variable L_K");
        current_statement__ = 18;
        assign(f, multiply(L_K, eta), "assigning variable f");
      }
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          vars__.emplace_back(f[(sym1__ - 1)]);
        }
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> mu;
      mu = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(mu, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 20;
      assign(mu,
        stan::math::exp(
          add(add(add(add(log_E, beta0), multiply(beta1, x)), f),
            multiply(theta, sigma_theta))), "assigning variable mu");
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(mu[(sym1__ - 1)]);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    int current_statement__ = 0; 
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double beta0;
      beta0 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      beta0 = context__.vals_r("beta0")[(1 - 1)];
      double beta1;
      beta1 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      beta1 = context__.vals_r("beta1")[(1 - 1)];
      double sigma_theta;
      sigma_theta = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      sigma_theta = context__.vals_r("sigma_theta")[(1 - 1)];
      double sigma_theta_free__;
      sigma_theta_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      sigma_theta_free__ = stan::math::lb_free(sigma_theta, 0);
      Eigen::Matrix<double, -1, 1> theta;
      theta = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(theta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> theta_flat__;
        current_statement__ = 4;
        theta_flat__ = context__.vals_r("theta");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 4;
          assign(theta, theta_flat__[(pos__ - 1)],
            "assigning variable theta", index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      double rho;
      rho = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      rho = context__.vals_r("rho")[(1 - 1)];
      double rho_free__;
      rho_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      rho_free__ = stan::math::lb_free(rho, 0);
      double alpha;
      alpha = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 6;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      double alpha_free__;
      alpha_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 6;
      alpha_free__ = stan::math::lb_free(alpha, 0);
      Eigen::Matrix<double, -1, 1> eta;
      eta = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(eta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> eta_flat__;
        current_statement__ = 7;
        eta_flat__ = context__.vals_r("eta");
        current_statement__ = 7;
        pos__ = 1;
        current_statement__ = 7;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 7;
          assign(eta, eta_flat__[(pos__ - 1)],
            "assigning variable eta", index_uni(sym1__));
          current_statement__ = 7;
          pos__ = (pos__ + 1);
        }
      }
      vars__.emplace_back(beta0);
      vars__.emplace_back(beta1);
      vars__.emplace_back(sigma_theta_free__);
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(theta[(sym1__ - 1)]);
      }
      vars__.emplace_back(rho_free__);
      vars__.emplace_back(alpha_free__);
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(eta[(sym1__ - 1)]);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"beta0", "beta1", "sigma_theta",
      "theta", "rho", "alpha", "eta", "f", "mu"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(N)}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "beta0");
    param_names__.emplace_back(std::string() + "beta1");
    param_names__.emplace_back(std::string() + "sigma_theta");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "rho");
    param_names__.emplace_back(std::string() + "alpha");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "eta" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "f" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "beta0");
    param_names__.emplace_back(std::string() + "beta1");
    param_names__.emplace_back(std::string() + "sigma_theta");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "theta" + '.' + std::to_string(sym1__));
      } 
    }
    param_names__.emplace_back(std::string() + "rho");
    param_names__.emplace_back(std::string() + "alpha");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "eta" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "f" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"beta0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_theta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"f\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"beta0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta1\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_theta\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"eta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"f\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec;
      vars_vec.reserve(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars,
       emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec;
      params_r_vec.reserve(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }

};
}
using stan_model = counts_kriging_model_namespace::counts_kriging_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return counts_kriging_model_namespace::profiles__;
}

#endif


